import type { TValue } from './registry';


// Copied from https://github.com/bevyengine/bevy/blob/main/tools/publish.sh
export const bevyTypes = {
    ENTITY: 'bevy_ecs::entity::Entity',
    PARENT: 'bevy_hierarchy::components::parent::Parent',
    CHILDREN: 'bevy_hierarchy::components::children::Children',
    NAME: 'bevy_core::name::Name',
    CAMERA_3D: 'bevy_core_pipeline::core_3d::camera_3d::Camera3d',
    POINT_LIGHT: 'bevy_pbr::light::point_light::PointLight',
    MESH_3D: 'bevy_render::mesh::components::Mesh3d',
    OBSERVER: 'bevy_ecs::observer::runner::Observer',
    WINDOW: 'bevy_window::window::Window',
    SYSTEM_ID_MARKER: 'bevy_ecs::system::system_registry::SystemIdMarker',
    MONITOR: 'bevy_window::monitor::Monitor',
    PRIMARY_MONITOR: 'bevy_window::monitor::PrimaryMonitor',
    POINTER_ID: 'bevy_picking::pointer::PointerId',
    COMPUTED_NODE: 'bevy_ui::ui_node::ComputedNode',
    NODE: 'bevy_ui::ui_node::Node',
    TEXT: 'bevy_ui::widget::text::Text',
    TEXT_LAYOUT_INFO: 'bevy_text::pipeline::TextLayoutInfo',
    GLOBAL_TRANSFORM: 'bevy_transform::components::global_transform::GlobalTransform',
    VIEW_VISIBILITY: 'bevy_render::view::visibility::ViewVisibility',
    VISIBILITY: 'bevy_render::view::visibility::Visibility',
    COLOR: 'bevy_color::color::Color',
};

// Copied from https://github.com/bevyengine/bevy/blob/main/tools/publish.sh
export const bevyCrates = [
    'bevy_utils',
    'bevy_ptr',
    'bevy_macro_utils',
    'bevy_derive',
    'bevy_math',
    'bevy_color',
    'bevy_tasks',
    'bevy_reflect',
    'bevy_ecs',
    'bevy_state',
    'bevy_app',
    'bevy_time',
    'bevy_log',
    'bevy_asset',
    'bevy_audio',
    'bevy_core',
    'bevy_diagnostic',
    'bevy_hierarchy',
    'bevy_transform',
    'bevy_window',
    'bevy_render',
    'bevy_mikktspace',
    'bevy_image',
    'bevy_mesh',
    'bevy_core_pipeline',
    'bevy_input',
    'bevy_gilrs',
    'bevy_animation',
    'bevy_pbr',
    'bevy_gltf',
    'bevy_remote',
    'bevy_scene',
    'bevy_picking',
    'bevy_sprite',
    'bevy_gizmos',
    'bevy_text',
    'bevy_a11y',
    'bevy_ui',
    'bevy_winit',
    'bevy_dev_tools',
    'bevy_internal',
    'bevy_dylib',
];

export const COMMON_NAMES: Record<string, string | ((value: TValue) => string)> = {
    [bevyTypes.CAMERA_3D]: 'Camera3d',
    [bevyTypes.POINT_LIGHT]: 'PointLight',
    [bevyTypes.MESH_3D]: 'Mesh3d',
    [bevyTypes.OBSERVER]: 'Observer',
    [bevyTypes.WINDOW]: 'Window',
    [bevyTypes.PRIMARY_MONITOR]: 'PrimaryMonitor',
    [bevyTypes.MONITOR]: 'Monitor',
    [bevyTypes.POINTER_ID]: (val) => ` PointerId (${val as string})`,
    [bevyTypes.TEXT]: 'Text',
    [bevyTypes.NODE]: 'Node',
};