import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { EventTimingSample, LatencySample, TrialResult } from '../shared/protocol';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '../..');
const resultsDir = resolve(projectRoot, 'results');
const outputPath = resolve(projectRoot, 'src/generated/results-data.ts');

interface CompactResult {
  file: string;
  app: string;
  path: string;
  startedAtIso: string;
  refreshHzEstimate: number | null;
  sampleCount: number;
  summary: TrialResult['summary'];
  latenciesMs: number[];
  errorsPx: number[];
  draggingLatenciesMs: number[];
  draggingErrorsPx: number[];
  relativeLatenciesMs: number[];
  relativeErrorsPx: number[];
  draggingRelativeLatenciesMs: number[];
  draggingRelativeErrorsPx: number[];
  inputAgeMs: number[];
  frameIntervalsMs: number[];
  timingCounts: Record<string, number>;
  phaseCounts: Record<string, number>;
}

async function main() {
  const files = (await readdir(resultsDir)).filter((file) => file.endsWith('.json')).sort();
  const compact: CompactResult[] = [];
  for (const file of files) {
    const result = JSON.parse(await readFile(resolve(resultsDir, file), 'utf8')) as TrialResult;
    compact.push(compactResult(file, result));
  }

  await mkdir(dirname(outputPath), { recursive: true });
  const source = `// Generated by npm run analyze. Do not edit by hand.
export interface CompactAnalysisResult {
  file: string;
  app: string;
  path: string;
  startedAtIso: string;
  refreshHzEstimate: number | null;
  sampleCount: number;
  summary: {
    sampleCount: number;
    p50LatencyMs: number | null;
    p95LatencyMs: number | null;
    maxLatencyMs: number | null;
    meanErrorPx: number | null;
    maxErrorPx: number | null;
  };
  latenciesMs: number[];
  errorsPx: number[];
  draggingLatenciesMs: number[];
  draggingErrorsPx: number[];
  relativeLatenciesMs: number[];
  relativeErrorsPx: number[];
  draggingRelativeLatenciesMs: number[];
  draggingRelativeErrorsPx: number[];
  inputAgeMs: number[];
  frameIntervalsMs: number[];
  timingCounts: Record<string, number>;
  phaseCounts: Record<string, number>;
}

export const ANALYSIS_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};
export const ANALYSIS_RESULTS: CompactAnalysisResult[] = ${JSON.stringify(compact, null, 2)};
`;
  await writeFile(outputPath, source);
  console.log(`Wrote ${compact.length} compact result(s) to ${outputPath}`);
}

function compactResult(file: string, result: TrialResult): CompactResult {
  const samples = result.samples;
  const pointerTimings = result.timings
    .filter((timing) => timing.ty === 'pointer')
    .sort((a, b) => a.t - b.t);

  return {
    file,
    app: result.app,
    path: result.path,
    startedAtIso: result.startedAtIso,
    refreshHzEstimate: result.refreshHzEstimate,
    sampleCount: samples.length,
    summary: result.summary,
    latenciesMs: samples
      .map((sample) => sample.estimatedLatencyMs)
      .filter((value): value is number => value !== null && Number.isFinite(value))
      .map(round2),
    errorsPx: samples.map((sample) => round2(sample.errorPx)),
    draggingLatenciesMs: samples
      .filter((sample) => sample.phase === 'dragging')
      .map((sample) => sample.estimatedLatencyMs)
      .filter((value): value is number => value !== null && Number.isFinite(value))
      .map(round2),
    draggingErrorsPx: samples
      .filter((sample) => sample.phase === 'dragging')
      .map((sample) => round2(sample.errorPx)),
    relativeLatenciesMs: samples
      .map((sample) => sample.relativeLatencyMs)
      .filter((value): value is number => value !== null && value !== undefined && Number.isFinite(value))
      .map(round2),
    relativeErrorsPx: samples
      .map((sample) => sample.relativeErrorPx)
      .filter((value): value is number => value !== undefined && Number.isFinite(value))
      .map(round2),
    draggingRelativeLatenciesMs: samples
      .filter((sample) => sample.phase === 'dragging')
      .map((sample) => sample.relativeLatencyMs)
      .filter((value): value is number => value !== null && value !== undefined && Number.isFinite(value))
      .map(round2),
    draggingRelativeErrorsPx: samples
      .filter((sample) => sample.phase === 'dragging')
      .map((sample) => sample.relativeErrorPx)
      .filter((value): value is number => value !== undefined && Number.isFinite(value))
      .map(round2),
    inputAgeMs: computeInputAge(samples, pointerTimings).map(round2),
    frameIntervalsMs: computeFrameIntervals(samples).map(round2),
    timingCounts: countTimings(result.timings),
    phaseCounts: countPhases(samples),
  };
}

function computeInputAge(samples: LatencySample[], pointerTimings: EventTimingSample[]) {
  const ages: number[] = [];
  let pointerIndex = 0;
  for (const sample of samples) {
    while (pointerIndex + 1 < pointerTimings.length && pointerTimings[pointerIndex + 1].t <= sample.t) {
      pointerIndex++;
    }
    const pointer = pointerTimings[pointerIndex];
    if (pointer && pointer.t <= sample.t) {
      ages.push(sample.t - pointer.t);
    }
  }
  return ages.filter((value) => Number.isFinite(value) && value >= 0);
}

function computeFrameIntervals(samples: LatencySample[]) {
  const intervals: number[] = [];
  for (let i = 1; i < samples.length; i++) {
    intervals.push(samples[i].t - samples[i - 1].t);
  }
  return intervals.filter((value) => Number.isFinite(value) && value > 0);
}

function countTimings(timings: EventTimingSample[]) {
  const counts: Record<string, number> = {};
  for (const timing of timings) {
    counts[timing.ty] = (counts[timing.ty] || 0) + 1;
  }
  return counts;
}

function countPhases(samples: LatencySample[]) {
  const counts: Record<string, number> = {};
  for (const sample of samples) {
    const phase = sample.phase || (sample.dragging ? 'dragging' : 'idle');
    counts[phase] = (counts[phase] || 0) + 1;
  }
  return counts;
}

function round2(value: number) {
  return Math.round(value * 100) / 100;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
